# Site settings
title: Slides
description: "Slides from presentations I've given over the past several years."
baseurl: "/clojure-intro"
url: "https://benizi.github.io" # the base hostname & protocol for your site
twitter_username: benizi
github_username: benizi

# Build settings
markdown: kramdown
