source 'https://rubygems.org'
gem 'activesupport', '~> 3.2.12'
gem 'coderay'
gem 'haml'
gem 'github-linguist', :github => 'github/linguist', :require => 'linguist'
gem 'pygments.rb', :github => 'tmm1/pygments.rb'
